services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    build: .
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_APPLICATION_JSON: >-
        {
          "spring.datasource.url": "jdbc:mysql://db:${MYSQLDB_DOCKER_PORT}/${MYSQL_DATABASE}",
          "spring.datasource.username": "root",
          "spring.datasource.password": "${MYSQLDB_ROOT_PASSWORD}",
          "spring.jpa.hibernate.ddl-auto": "update",
          "spring.jpa.show-sql": "true",
          "spring.jpa.open-in-view": "false",
          "server.error.include-binding-errors": "always",
          "server.error.include-message": "always",
          "jwt.expiration": "500000",
          "jwt.secret": "superdupersecretsuperdupersecretsuperdupersecret"
        }
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"
    volumes:
      - .m2:/root/.m2

volumes:
  db_data:
